name: plexus-run
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10,<3.14
  - blast>=2.12.0
  - pip
  - pip:
    - biopython
    - loguru
    - pandas
    - primer3-py>=2.2.0
    - pydantic
    - pysam>=0.19.0
    - rich
    - typer
